[tool.poetry]
name = "template"
version = "0.1.0"
description = ""
authors = ["Evan Relf <evan@evanrelf.com>"]
license = "ISC"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
